activePage = null
usersUrl = null

removeUser = (url) ->
  $.confirm
    text: 'Вы действительно хотите удалить пользователя?'
    confirm: (button) ->
      $.post url, { csrfmiddlewaretoken: csrftoken }, (data) ->
        window.location = data.redirect_url
        return
      return
    title: 'Удаление пользователя'
    confirmButton: 'Удалить'
    cancelButton: 'Отмена'
  return

prev = ->
  search = $('#search').val()
  activePage = if activePage == 0 then activePage else activePage - 1
  document.location = usersUrl + '?page=' + activePage + ';search=' + search
  return

next = ->
  search = $('#search').val()
  current = $('li.active[data-pagi=\'true\']')
  if !current.attr('data-max')
    activePage = activePage + 1
  document.location = usersUrl + '?page=' + activePage + ';search=' + search
  return

pagi = (ind) ->
  search = $('#search').val()
  document.location = usersUrl + '?page=' + ind + ';search=' + search
  return

search = ->
  `var search`
  search = $('#search').val()
  document.location = usersUrl + '?search=' + search
  return

clearImage = ->
    $('#profile_img').attr('src', "/assets/system/dist/img/anonymous-160x160.gif")
    $("#fileupload").val('')
    $('#fileupload_avatar').val('')
    $('#add-btn').show()
    $('#clear-btn').hide()
    return

previewImage = (event) ->
    input = event.target
    if (input.files && input.files[0])
        reader = new FileReader()
        reader.onload = (e) ->
            $('#profile_img').attr('src', e.target.result)
            # вспомогательная штука, чтоб узнать изменили ли авку
            $('#fileupload_avatar').val(e.target.result)
            return

        reader.readAsDataURL(input.files[0]);

        $('#add-btn').hide();
        $('#clear-btn').show();

$(document).ready ->
  activePage = $('#active_num').val()
  usersUrl = $('#users_table').attr('data-url')
  $('[name="birth_date"]').datepicker
    format: 'yyyy-mm-dd'
    autoclose: true
    forseParse: false
    keyboardNavigation: false
  $('[name="phone"]').inputmask '99999999999'
  if $('#fileupload')
    $("#fileupload").on('change',previewImage);
  return

# ---
# generated by js2coffee 2.1.0
